# Generated by Django 5.0.8 on 2024-12-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_copy_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identification_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
